### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_playing'

### ISSUE THREAD

**Issue by Arief47** [eric-yeung/Discord-Bot-Test#9]
I've been balding my head for 5 hours wondering why this happen. anyone care to explain? I did installed all dependencies. Apologies in advance

`Bot online
Ignoring exception in command play:
Traceback (most recent call last):
  File "C:\Users\ahmad\PycharmProjects\Discord bot\venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\ahmad\PycharmProjects\Discord bot\Rihito bot.py", line 41, in play
    if not voice.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ahmad\PycharmProjects\Discord bot\venv\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\ahmad\PycharmProjects\Discord bot\venv\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\ahmad\PycharmProjects\Discord bot\venv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'is_playing'
`

**Comment by benniestudios** [comment]
I have the exact same problem. Does anyone know what I could try?
